import type { AppConfigPublic } from "./types";

export const appConfig: AppConfigPublic = {
  projectName: "Harune",
  projectSlug: "harune",
  url: "https://harune.me",
  keywords: [
    "Harune",
    "Harune link in bio",
    "Harune bio link",
    "link in bio",
    "link-in-bio tool",
    "link in bio tool",
    "link in bio app",
    "link in bio website",
    "free link in bio",
    "bio link",
    "bio link tool",
    "bio link page",
    "bio site",
    "profile link",
    "profile link page",
    "social link page",
    "social links",
    "multiple links in bio",
    "one link for all links",
    "Instagram link in bio",
    "Instagram bio link",
    "TikTok link in bio",
    "TikTok bio link",
    "YouTube link in bio",
    "creator link page",
    "creator hub",
    "creator page",
    "creator website",
    "custom creator page",
    "personal profile page",
    "online profile page",
    "profile page",
    "personal landing page",
    "mobile landing page",
    "customizable bio page",
    "link page analytics",
    "social media landing page",
    "Linktree alternative",
    "Beacons alternative",
    "bio.link alternative",
    "Lnk.Bio alternative",
    "Campsite.bio alternative",
    "Taplink alternative",
    "Carrd alternative",
    "링크 인 바이오",
    "링크인바이오",
    "바이오 링크",
    "프로필 링크",
    "인스타 링크",
    "인스타그램 링크",
    "인스타그램 프로필 링크",
    "틱톡 링크",
    "유튜브 링크",
    "링크 모음",
    "링크 모음 페이지",
    "링크트리 대체",
    "크리에이터 프로필",
    "크리에이터 링크",
    "개인 프로필 페이지",
  ],
  description: "Harune is a link-in-bio service for sharing everything you do in one place.",
  auth: {
    enablePasswordAuth: false, // Set to true to enable password-based authentication
  },
  legal: {
    address: {
      street: "Plot No 337, Workyard, Phase 2, Industrial Business &amp; Park",
      city: "Chandigarh",
      state: "Punjab",
      postalCode: "160002",
      country: "India",
    },
    email: "ssent.hq@gmail.com",
    phone: "+91 9876543210",
  },
  social: {
    twitter: "https://twitter.com/cjsingg",
    instagram: "https://instagram.com/-",
    linkedin: "https://linkedin.com/-",
    facebook: "https://facebook.com/-",
    youtube: "https://youtube.com/-",
  },
  email: {
    senderName: "Harune",
    senderEmail: "ssent.hq@gmail.com",
  },
};
