import { readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const httpOutputDir = path.resolve("src/lib/api/generated/http");
const schemaDir = path.join(httpOutputDir, "schemas");

const orvalHeader = [
  "/**",
  " * Generated by orval v8.9.1 🍺",
  " * Do not edit manually.",
  " * Harune API",
  " * API documentation for Harune",
  " * OpenAPI spec version: 1.0.0",
  " */",
].join("\n");

const schemaImportLinePattern = /^import type \{[^}]+\} from "\.\/([^"]+)";\n?/gm;
const leafSchemaImportPattern = /^import type \{[^}]+\} from "\.\/([^"]+)";$/;
const clientSchemaImportPattern = /^import type \{([^}]+)\} from "\.\.\/schemas\/([^"]+)";$/;

const normalizeNewlines = (value: string) => value.replace(/\r\n/g, "\n");

const stripGeneratedHeader = (content: string) => {
  const headerEnd = content.indexOf("*/");

  if (headerEnd === -1) {
    return content.trimStart();
  }

  return content.slice(headerEnd + 2).trimStart();
};

const stripSchemaImports = (content: string) =>
  content
    .replace(schemaImportLinePattern, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

const unique = <T>(items: T[]) => [...new Set(items)];

const listApiModules = async () => {
  const entries = await readdir(httpOutputDir, { withFileTypes: true });

  return entries
    .filter((entry) => entry.isDirectory() && entry.name.endsWith("-api"))
    .map((entry) => entry.name)
    .sort();
};

const listSchemaFiles = async () => {
  const entries = await readdir(schemaDir, { withFileTypes: true });

  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".ts"))
    .map((entry) => entry.name)
    .sort();
};

const toPascalCase = (value: string) =>
  value
    .split("-")
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join("");

const formatTypeImport = (typeNames: string[], source: string) => {
  const names = unique(typeNames).sort((a, b) => a.localeCompare(b));

  if (names.length === 1) {
    return `import type { ${names[0]} } from "${source}";`;
  }

  return ["import type {", ...names.map((name) => `  ${name},`), `} from "${source}";`].join("\n");
};

const parseClientSchemaImports = (content: string) => {
  const imports: string[] = [];

  for (const line of normalizeNewlines(content).split("\n")) {
    const match = line.match(clientSchemaImportPattern);

    if (!match) {
      continue;
    }

    imports.push(match[2]);
  }

  return unique(imports);
};

const parseLeafSchemaImports = (content: string) => {
  const imports: string[] = [];

  for (const line of normalizeNewlines(content).split("\n")) {
    const match = line.match(leafSchemaImportPattern);

    if (!match) {
      continue;
    }

    imports.push(match[1]);
  }

  return unique(imports);
};

const buildSchemaGraph = async (schemaFiles: string[]) => {
  const graph = new Map<string, string[]>();

  for (const schemaFile of schemaFiles) {
    const content = await readFile(path.join(schemaDir, schemaFile), "utf8");
    const imports = parseLeafSchemaImports(content);

    graph.set(
      schemaFile,
      imports.map((dependency) => `${dependency}.ts`)
    );
  }

  return graph;
};

const collectDependencyOrder = (entryFiles: string[], graph: Map<string, string[]>) => {
  const ordered: string[] = [];
  const visited = new Set<string>();
  const visiting = new Set<string>();

  const visit = (fileName: string) => {
    if (visited.has(fileName)) {
      return;
    }

    if (visiting.has(fileName)) {
      throw new Error(
        `Circular schema dependency detected: ${[...visiting, fileName].join(" -> ")}`
      );
    }

    const deps = graph.get(fileName) ?? [];

    visiting.add(fileName);

    for (const dependency of deps) {
      visit(dependency);
    }

    visiting.delete(fileName);
    visited.add(fileName);
    ordered.push(fileName);
  };

  for (const entryFile of entryFiles) {
    visit(entryFile);
  }

  return ordered;
};

const rewriteClientFile = async (apiModule: string, importedSchemas: string[]) => {
  if (importedSchemas.length === 1 && importedSchemas[0] === apiModule) {
    return;
  }

  const clientFilePath = path.join(httpOutputDir, apiModule, `${apiModule}.ts`);
  const rawContent = await readFile(clientFilePath, "utf8");
  const normalizedContent = normalizeNewlines(rawContent);
  const schemaImportLine = formatTypeImport(
    importedSchemas.map((schemaFile) => toPascalCase(schemaFile)),
    `../schemas/${apiModule}`
  );

  const withoutLeafImports = normalizedContent
    .replace(/^import type \{[^}]+\} from "\.\.\/schemas\/[^"]+";\n?/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd();

  const mutatorImportLine = 'import { orvalMutator } from "../../../orval-mutator";';

  if (!withoutLeafImports.includes(mutatorImportLine)) {
    throw new Error(`Unable to locate mutator import in ${clientFilePath}`);
  }

  const rewritten = withoutLeafImports
    .replace(`${mutatorImportLine}\n`, `${mutatorImportLine}\n${schemaImportLine}\n`)
    .replace(
      / {2}Object\.entries\(params \|\| {}\)\.forEach\(\(\[key, value\]\) => \{\n([\s\S]*?) {2}\}\);\n/g,
      "  for (const [key, value] of Object.entries(params || {})) {\n$1  }\n"
    );

  await writeFile(clientFilePath, `${rewritten.trimEnd()}\n`, "utf8");
};

const buildAggregateSchemaFile = async (apiModule: string, orderedSchemaFiles: string[]) => {
  const outputPath = path.join(schemaDir, `${apiModule}.ts`);
  const sections: string[] = [orvalHeader];

  for (const schemaFile of orderedSchemaFiles) {
    const content = await readFile(path.join(schemaDir, schemaFile), "utf8");
    const body = stripSchemaImports(stripGeneratedHeader(normalizeNewlines(content)));

    if (body.length > 0) {
      sections.push(body);
    }
  }

  await writeFile(outputPath, `${sections.join("\n\n")}\n`, "utf8");
};

const main = async () => {
  const apiModules = await listApiModules();
  const schemaFiles = await listSchemaFiles();
  const schemaGraph = await buildSchemaGraph(schemaFiles);

  for (const apiModule of apiModules) {
    const clientFilePath = path.join(httpOutputDir, apiModule, `${apiModule}.ts`);
    const clientContent = await readFile(clientFilePath, "utf8");
    const importedSchemas = parseClientSchemaImports(clientContent);
    const rootSchemaFiles = importedSchemas.map((schemaFile) => `${schemaFile}.ts`);
    const orderedSchemaFiles = collectDependencyOrder(rootSchemaFiles, schemaGraph);

    await buildAggregateSchemaFile(apiModule, orderedSchemaFiles);
    await rewriteClientFile(apiModule, importedSchemas);
  }

  const keepFiles = new Set(apiModules.map((apiModule) => `${apiModule}.ts`));

  for (const schemaFile of schemaFiles) {
    if (keepFiles.has(schemaFile)) {
      continue;
    }

    await rm(path.join(schemaDir, schemaFile));
  }

  console.log(
    `Merged ${schemaFiles.length} generated schema files into ${apiModules.length} domain files.`
  );
};

await main();
