import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

const defaultApiBaseUrl =
  process.env.NODE_ENV === "development" ? "http://localhost:8787" : "https://api.harune.me";

export const env = createEnv({
  server: {
    AUTH_SECRET: z.string().optional(),
    BETTER_AUTH_SECRET: z.string().optional(),
    BETTER_AUTH_URL: z.string().optional(),
    AWS_ACCESS_KEY_ID: z.string().optional(),
    AWS_BUCKET_NAME: z.string().optional(),
    AWS_REGION: z.string().optional(),
    AWS_S3_BUCKET_NAME: z.string().optional(),
    AWS_SECRET_ACCESS_KEY: z.string().optional(),
    DODO_CREDITS_PRODUCT_ID: z.string().optional(),
    DODO_PAYMENTS_API_KEY: z.string().optional(),
    DODO_PAYMENTS_API_URL: z.string().optional(),
    DODO_PAYMENTS_WEBHOOK_SECRET: z.string().optional(),
    GOOGLE_CLIENT_ID: z.string().optional(),
    GOOGLE_CLIENT_SECRET: z.string().optional(),
    LEMONSQUEEZY_API_KEY: z.string().optional(),
    LEMONSQUEEZY_TEST_MODE: z.string().optional(),
    PADDLE_API_KEY: z.string().optional(),
    PADDLE_CREDITS_PRODUCT_ID: z.string().optional(),
    PADDLE_WEBHOOK_SECRET: z.string().optional(),
    PAYPAL_SECRET_KEY: z.string().optional(),
    PAYPAL_WEBHOOK_ID: z.string().optional(),
    R2_ACCESS_KEY_ID: z.string().optional(),
    R2_ACCOUNT_ID: z.string().optional(),
    R2_BUCKET_NAME: z.string().optional(),
    R2_PUBLIC_BASE_URL: z.string().optional(),
    R2_SECRET_ACCESS_KEY: z.string().optional(),
    SENTRY_AUTH_TOKEN: z.string().optional(),
    SENTRY_ORG: z.string().optional(),
    SENTRY_PROJECT: z.string().optional(),
    SERVER_API_BASE_URL: z.string().url().optional(),
    SESSION_SECRET: z.string().optional(),
    STRIPE_SECRET_KEY: z.string().optional(),
    STRIPE_WEBHOOK_SECRET: z.string().optional(),
    SUPABASE_S3_ACCESS_KEY_ID: z.string().optional(),
    SUPABASE_S3_BUCKET: z.string().optional(),
    SUPABASE_S3_BUCKET_NAME: z.string().optional(),
    SUPABASE_S3_ENDPOINT: z.string().optional(),
    SUPABASE_S3_REGION: z.string().optional(),
    SUPABASE_S3_SECRET_ACCESS_KEY: z.string().optional(),
    UMAMI_API_ENDPOINT: z.string().optional(),
    UMAMI_API_KEY: z.string().optional(),
    UMAMI_API_TOKEN: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_ANALYTICS_PROVIDER: z.string().optional(),
    NEXT_PUBLIC_APP_URL: z.string().optional(),
    NEXT_PUBLIC_API_BASE_URL: z.string().url().default(defaultApiBaseUrl),
    NEXT_PUBLIC_BETTERLYTICS_SCRIPT_SRC: z.string().optional(),
    NEXT_PUBLIC_BETTERLYTICS_SITE_ID: z.string().optional(),
    NEXT_PUBLIC_PADDLE_CLIENT_TOKEN: z.string().optional(),
    NEXT_PUBLIC_PADDLE_ENV: z.string().optional(),
    NEXT_PUBLIC_PAYPAL_CLIENT_ID: z.string().optional(),
    NEXT_PUBLIC_PAYPAL_IS_SANDBOX: z.string().optional(),
    NEXT_PUBLIC_SENTRY_DSN: z.string().optional(),
    NEXT_PUBLIC_SIGNIN_ENABLED: z.string().optional(),
    NEXT_PUBLIC_UMAMI_SCRIPT_SRC: z.string().optional(),
    NEXT_PUBLIC_UMAMI_WEBSITE_ID: z.string().optional(),
  },
  experimental__runtimeEnv: {
    NEXT_PUBLIC_ANALYTICS_PROVIDER: process.env.NEXT_PUBLIC_ANALYTICS_PROVIDER,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
    NEXT_PUBLIC_BETTERLYTICS_SCRIPT_SRC: process.env.NEXT_PUBLIC_BETTERLYTICS_SCRIPT_SRC,
    NEXT_PUBLIC_BETTERLYTICS_SITE_ID: process.env.NEXT_PUBLIC_BETTERLYTICS_SITE_ID,
    NEXT_PUBLIC_PADDLE_CLIENT_TOKEN: process.env.NEXT_PUBLIC_PADDLE_CLIENT_TOKEN,
    NEXT_PUBLIC_PADDLE_ENV: process.env.NEXT_PUBLIC_PADDLE_ENV,
    NEXT_PUBLIC_PAYPAL_CLIENT_ID: process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID,
    NEXT_PUBLIC_PAYPAL_IS_SANDBOX: process.env.NEXT_PUBLIC_PAYPAL_IS_SANDBOX,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
    NEXT_PUBLIC_SIGNIN_ENABLED: process.env.NEXT_PUBLIC_SIGNIN_ENABLED,
    NEXT_PUBLIC_UMAMI_SCRIPT_SRC: process.env.NEXT_PUBLIC_UMAMI_SCRIPT_SRC,
    NEXT_PUBLIC_UMAMI_WEBSITE_ID: process.env.NEXT_PUBLIC_UMAMI_WEBSITE_ID,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
